### ISSUE TITLE
Styling of input/forms

### ISSUE THREAD

**Issue by Niek** [bradleytaunt/vanilla-css#2]
Would be nice to have some kind of extra styling for form inputs. For example:
```css
input {
  border:#000 1px solid var(--primary-color);
  padding: 0.5rem;
  background-color: var(--secondary-color);
}
```
